### ISSUE TITLE
module 'lib.clients.Basic' has no attribute 'Client'

### ISSUE THREAD

**Issue by fadiaburaid** [command-z-z/CarlaDataCollector#1]
I am trying CarlaDataCollector but I am facing problem with my first try.
I am getting the following error. 

```
(Carla_Sim) E:\Carla 0.9.15\CarlaDataCollector-main>python generator.py
EXP NAME:  3d-object
Traceback (most recent call last):
  File "generator.py", line 25, in <module>
    main()
  File "generator.py", line 7, in main
    client = make_client(cfg)
  File "E:\Carla 0.9.15\CarlaDataCollector-main\lib\clients\make_client.py", line 6, in make_client
    client = imp.load_source(module, path).Client(cfg)
AttributeError: module 'lib.clients.Basic' has no attribute 'Client'
```

**Comment by command-z-z** [comment]
Actually, when you run `python generator.py` is a basic script(Not recommended use), you should write a specific configuration for your specific task. You can refer to this [usage section](https://github.com/command-z-z/CarlaDataCollector?tab=readme-ov-file#-usage) and my [specific task](https://github.com/command-z-z/CarlaDataCollector?tab=readme-ov-file#-example) with specific config `python generator.py --cfg_file ./configs/kitti/3d-lidar.yaml`.
I will fix this error and refacotr repo in my free time, thank you for your try:)
